# https://deepsource.io/docs/config/deepsource-toml.html
# https://deepsource.io/docs/analyzer/python.html

version = 1

test_patterns = [
  "slackminion/tests/*.py",
  "slackminion/tests/**/*.py",
]

exclude_patterns = [
  "setup.py",
  "docs/**",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
  # TODO: Enable type checker
  # type_checker = "mypy"
